// GENERATED by sdk/build.py from openapi.json v1.15.2 — do not edit by hand.
import { MindUploadBase } from "./client";
import type { Result } from "./client";
import { ApiError, MindUploadConnectionError, MindUploadError } from "./errors";

export type ExternalAuthorizationStatus = "pending" | "slow_down" | "denied" | "expired" | "revoked" | "exchanged";

export interface WaitForExternalAuthorizationParams {
  deviceCode: string;
  timeoutMs?: number;
}

export interface WaitForExternalCloneInvocationParams extends InvokeExternalCloneParams {
  timeoutMs?: number;
}

const DEFAULT_AUTHORIZATION_POLL_MS = 5000;
const MAX_PENDING_POLL_MS = 15000;
const MAX_SLOW_DOWN_POLL_MS = 30000;
const SLOW_DOWN_INCREMENT_MS = 5000;
const POLL_JITTER_RATIO = 0.2;

const DEFAULT_INVOCATION_POLL_MS = 2000;
const MAX_INVOCATION_POLL_MS = 10000;
const EXTERNAL_INVOCATION_PROCESSING_STATUS = "processing";
// Transient gateway faults worth replaying an idempotent invocation through;
// a slow in-request clone reply can surface as one of these (or a timeout).
const INVOCATION_RETRY_STATUSES = new Set([502, 503, 504]);

export interface CreateCloneParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  nickname?: string;
  gender?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
  reinforcementLearning?: boolean;
}

export interface GetClonesParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
}

export interface UpdateCloneParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  nickname?: string;
  gender?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
  autoKeepExternalMemories?: boolean;
  reinforcementLearning?: boolean;
}

export interface GetQuotaParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
}

export interface CheckUsernameParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
}

export interface LoginParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Optional. A stable identifier for the device or app install signing in. Send the same value every time from one install: a new sign-in then replaces only the earlier session of that install and leaves the other devices of the user signed in. */
  visitorId?: string;
}

export interface LogoutParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
}

export interface RegisterParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  email?: string;
  emailVerificationCode?: string;
  firstName?: string;
  lastName?: string;
  nickname?: string;
  gender?: string;
  birthDate?: number;
  phoneNumber?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
  /** Optional. The same device or app install identifier as for login; the first session of the new account is kept under it. */
  visitorId?: string;
}

export interface CheckChatroomUpdatesParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Rooms to check. Each entry must include `chatroom_id`; include `known_updated_at` from the previous response, or null/omit it on the first poll. */
  chatrooms?: Array<Record<string, unknown>>;
}

export interface CreateChatroomParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  chatroomName?: string;
  isPublic?: boolean;
  avatarId?: string;
  soulmateCheckEnabled?: boolean;
}

export interface CreateChatroomMembershipParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
  inviteeUsername?: string;
  inviteeCodename?: string;
  adminLevel?: string;
}

export interface CreateChatroomMessageParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
  text?: string;
}

export interface GetChatroomMembershipParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  page?: number;
  /** Maximum records requested for one server-capped page. */
  pageSize?: number;
  sortBy?: string;
  /** Sort direction; supported values depend on the operation. */
  sortOrder?: number;
  useCursorPagination?: boolean;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: string;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
}

export interface GetChatroomMessagesParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  page?: number;
  /** Maximum records requested for one server-capped page. */
  pageSize?: number;
  sortBy?: string;
  /** Sort direction; supported values depend on the operation. */
  sortOrder?: number;
  useCursorPagination?: boolean;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: string;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
  sinceValue?: number;
  sinceId?: string;
}

export interface GetChatroomMessagesAroundParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId: string;
  /** Chatroom message id. */
  messageId: string;
  /** How many earlier neighbors to include around the anchor id. */
  before?: number;
  /** How many later neighbors to include around the anchor id. */
  after?: number;
}

export interface GetChatroomsParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  page?: number;
  /** Maximum records requested for one server-capped page. */
  pageSize?: number;
  sortBy?: string;
  /** Sort direction; supported values depend on the operation. */
  sortOrder?: number;
  useCursorPagination?: boolean;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: string;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  getPublic?: boolean;
  getPrivate?: boolean;
}

export interface SearchChatroomMessagesParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId: string;
  /** Optional find query. Whole-word tokens across alphabetic and numeric scripts; character phrases for Chinese / Japanese / Korean; mixed language supported. */
  keyword?: string;
  /** Optional list of media kinds to match: `image`, `video`, and/or `audio`. */
  contentMediaTypes?: Array<"image" | "video" | "audio">;
  /** Optional lower bound on message time as a UNIX timestamp in seconds. */
  createdAfter?: number;
  /** Optional upper bound on message time as a UNIX timestamp in seconds. */
  createdBefore?: number;
  /** Message send-time order: `-1` newest first (default), `1` oldest first. */
  sortOrder?: -1 | 1;
  /** Optional human member id; only messages from that user match. Mutually exclusive with `sender_clone_id`. */
  senderUserId?: string;
  /** Optional AI member id; only messages from that AI match. Mutually exclusive with `sender_user_id`. */
  senderCloneId?: string;
  /** Maximum Find hits for one page. */
  pageSize?: number;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: number;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
}

export interface TranslateChatroomMessageParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
  /** Chatroom message id. */
  messageId?: string;
}

export interface GetChatParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  page?: number;
  /** Maximum records requested for one server-capped page. */
  pageSize?: number;
  sortBy?: string;
  /** Sort direction; supported values depend on the operation. */
  sortOrder?: number;
  useCursorPagination?: boolean;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: string;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
}

export interface GetChatAroundParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password: string;
  /** Owner AI consciousness id from `get_clones` (required for one-on-one jump). */
  cloneId: string;
  /** One-on-one chat turn id. */
  chatId: string;
  /** How many earlier neighbors to include around the anchor id. */
  before?: number;
  /** How many later neighbors to include around the anchor id. */
  after?: number;
}

export interface RagParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  text?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
}

export interface SearchChatsParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password: string;
  /** Owner AI consciousness id from `get_clones` (required for one-on-one find). */
  cloneId: string;
  /** Optional find query. Whole-word tokens across alphabetic and numeric scripts; character phrases for Chinese / Japanese / Korean; mixed language supported. */
  keyword?: string;
  /** Optional list of media kinds to match: `image`, `video`, and/or `audio`. */
  contentMediaTypes?: Array<"image" | "video" | "audio">;
  /** Optional lower bound on message time as a UNIX timestamp in seconds. */
  createdAfter?: number;
  /** Optional upper bound on message time as a UNIX timestamp in seconds. */
  createdBefore?: number;
  /** Turn send-time order: `-1` newest first (default), `1` oldest first. */
  sortOrder?: -1 | 1;
  /** Optional 1v1 side filter: `user` (human), `assistant` (AI), or `both` (turns that include both sides). */
  side?: "user" | "assistant" | "both";
  /** Maximum Find hits for one page. */
  pageSize?: number;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: number;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
}

export interface TriggerSocialParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  membershipId?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
}

export interface CreateExternalAuthorizationRequestParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** A stable opaque event key that makes exact retries return the same outcome. */
  idempotencyKey: string;
  /** Your stable opaque identifier for this app installation. */
  installationId: string;
  /** Your stable opaque identifier for the person authorizing this installation. */
  externalSubject: string;
  /** Optional user-readable name for the installation shown during consent. */
  installationLabel?: string;
  /** Optional user-readable external identity shown during consent. */
  externalIdentityLabel?: string;
  /** Capabilities the owner is being asked to delegate. */
  requestedScopes: Array<"clone:invoke" | "clone:learn" | "clone:invoke_shared" | "clone:upload">;
}

export interface ExchangeExternalAuthorizationParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** Short-lived high-entropy secret used only to poll and exchange this request. */
  deviceCode: string;
}

export interface InspectExternalAuthorizationParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** Opaque grant token accepted only by grant inspection and external clone invocation; store it as a secret and never expose it to users. */
  accessToken: string;
}

export interface InvokeExternalCloneParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** Opaque grant token accepted only by grant inspection and external clone invocation; store it as a secret and never expose it to users. */
  accessToken: string;
  /** Your stable opaque identifier for this app installation. */
  installationId: string;
  /** Your stable opaque identifier for the person authorizing this installation. */
  externalSubject: string;
  /** AI consciousness id as returned by clone operations. */
  cloneId: string;
  text: string;
  /** A stable opaque event key that makes exact retries return the same outcome. */
  idempotencyKey: string;
  /** Stable opaque id of the conversation or thread this event belongs to. Each conversation keeps its own separate history; omit for a plain one-on-one event. */
  conversationId?: string;
  /** Neutral display name of whoever is sending this message, shown to the AI consciousness as who it is currently talking to. */
  speakerLabel?: string;
  /** Set true when this event is one turn of a multi-party conversation so the AI consciousness replies as a single participant among several. */
  isGroup?: boolean;
  /** Recent surrounding conversation for group mode (issue #172): an ordered, bounded list of prior turns the AI consciousness reads as quoted context. Each entry has a `display_name` and `text`, plus optional `is_ai`, `timestamp` (seconds), and `gender`. It carries no platform identifiers and is never treated as instructions. */
  contextMessages?: Array<Record<string, unknown>>;
  learn?: boolean;
  sourceLabel?: string;
}

export interface RefreshExternalAuthorizationParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** Opaque grant-lifetime token used only with refresh_external_authorization; store it as a secret. */
  refreshToken: string;
  /** Your stable opaque identifier for this app installation. */
  installationId: string;
  /** Your stable opaque identifier for the person authorizing this installation. */
  externalSubject: string;
}

export interface UploadExternalMindDataParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** Opaque grant token accepted only by grant inspection and external clone invocation; store it as a secret and never expose it to users. */
  accessToken: string;
  /** Your stable opaque identifier for this app installation. */
  installationId: string;
  /** Your stable opaque identifier for the person authorizing this installation. */
  externalSubject: string;
  /** AI consciousness id as returned by clone operations. */
  cloneId: string;
  text: string;
  textType?: "memory" | "persona" | "conscious";
  /** Optional. Accepted for forward compatibility but ignored for deduplication today — retries may create another quarantine item. Not a safe replay key. */
  idempotencyKey?: string;
  sourceLabel?: string;
}

export interface GetMindClusterParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  nodeId?: string;
  textsOffset?: number;
  textsPageSize?: number;
  forceRebuild?: boolean;
}

export interface GetSoulmateReportParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  myCloneId?: string;
  otherCloneId?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
}

export interface CreateCallSessionParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
  /** What kind of call to start. `conversation` (the default) admits everyone able to speak and show their camera. `broadcast` admits everyone except the chatroom owner and admins able to watch, listen and ask to speak, until somebody running the call lets them. Only the chatroom owner and admins may start a broadcast; anyone else asking for one starts a conversation. */
  mode?: "conversation" | "broadcast";
  /** Whether this call carries a picture. `video` (the default) is a call with cameras; `voice` is a call with none at all — sound only, which asks far less of a slow or metered connection. It is fixed for the whole call and applies to everybody in it — nobody can turn a camera on in a voice call, and nobody can join one as a video participant — so switching means starting a new call. Two things override it. A call already running in the room wins: the caller joins that one, in the kind it is already in. And `mode: broadcast` wins: a broadcast is always a video call, counted and capped as one. Read `media_tier` back off the call in the response to see which kind you got. */
  mediaTier?: "voice" | "video";
  /** Whether whoever starts this call runs it. False, and absent, mean the call controls rest only on chatroom standing — so a call whose owner and admins have all left carries on with nobody running it until one of them returns. Only the chatroom owner and admins may turn it on; anyone else asking for it is ignored. Set once, when the call starts. */
  hostInheritance?: boolean;
}

export interface EndCallSessionParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  callSessionId?: string;
  onlyIfEmpty?: boolean;
}

export interface GetActiveCallSessionParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Chatroom id as returned by chatroom operations. */
  chatroomId?: string;
}

export interface JoinCallSessionParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  callSessionId?: string;
}

export interface LeaveCallSessionParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  callSessionId?: string;
}

export interface RefreshCallTokenParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  callSessionId?: string;
}

export interface SetCallHostParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  callSessionId?: string;
  /** User id of the person whose standing in the call is changing. */
  targetUserId?: string;
  /** True to give that person the call controls for the length of this call; false to take them back. */
  runsTheCall?: boolean;
}

export interface AbortMultipartUploadParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Opaque media object key returned by upload-start operations and reused for multipart upload calls. */
  r2Key?: string;
  /** Multipart upload session id returned by `request_multipart_upload`. */
  uploadId?: string;
}

export interface CancelUploadParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Opaque media object key returned by upload-start operations and reused for multipart upload calls. */
  r2Key?: string;
}

export interface CompleteMultipartUploadParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Opaque media object key returned by upload-start operations and reused for multipart upload calls. */
  r2Key?: string;
  /** Multipart upload session id returned by `request_multipart_upload`. */
  uploadId?: string;
  /** The successfully uploaded parts, using the `part_number` and `etag` returned by each part upload. */
  parts?: Array<Record<string, unknown>>;
}

export interface ListUploadPartsParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Opaque media object key returned by upload-start operations and reused for multipart upload calls. */
  r2Key?: string;
  /** Multipart upload session id returned by `request_multipart_upload`. */
  uploadId?: string;
}

export interface RequestMultipartUploadParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  filename?: string;
  contentType?: string;
  fileSizeBytes?: number;
  /** The kind of media: `image`, `video`, or `audio`. */
  mediaType?: string;
  hasThumbnail?: boolean;
  thumbnailFileSizeBytes?: number;
}

export interface RequestUploadUrlParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  filename?: string;
  contentType?: string;
  fileSizeBytes?: number;
  /** The kind of media: `image`, `video`, or `audio`. */
  mediaType?: string;
  hasThumbnail?: boolean;
  thumbnailFileSizeBytes?: number;
}

export interface SignUploadPartParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Opaque media object key returned by upload-start operations and reused for multipart upload calls. */
  r2Key?: string;
  /** Multipart upload session id returned by `request_multipart_upload`. */
  uploadId?: string;
  /** One-based multipart part number. */
  partNumber?: number;
}

export interface SignUploadPartsBatchParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Opaque media object key returned by upload-start operations and reused for multipart upload calls. */
  r2Key?: string;
  /** Multipart upload session id returned by `request_multipart_upload`. */
  uploadId?: string;
  /** One-based multipart part numbers to sign in a single batch. */
  partNumbers?: Array<number>;
}

export interface StartMediaAnalysisParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password: string;
  /** The attachment to start describing, as its own call. Send each one as soon as it is uploaded or pasted, while the person is still typing, so nothing is left to do at send time. `maxItems` is the cap; a longer array is rejected, not truncated. */
  media: Array<Record<string, unknown>>;
  /** The AI consciousness this attachment is for, named the way `rag` and `get_chat` name it. Send this for a one-on-one conversation, or `chatroom_id` for a room — exactly one of the two, and the person must be able to reach it. */
  codename?: string;
  /** The chatroom this attachment is for, as returned by chatroom operations. Send this for a room, or `codename` for a one-on-one conversation — exactly one of the two, and the person must already be in the room. */
  chatroomId?: string;
}

export interface CreateTextParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  /** AI consciousness id as returned by clone operations. */
  cloneId?: string;
  /** The mind data itself. At most 50000 characters, counted in Unicode code points; longer text is rejected with 400 and nothing is stored. */
  text?: string;
  type?: "memory" | "persona" | "conscious";
}

export interface GetTextsParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  page?: number;
  /** Maximum records requested for one server-capped page. */
  pageSize?: number;
  sortBy?: string;
  /** Sort direction; supported values depend on the operation. */
  sortOrder?: number;
  useCursorPagination?: boolean;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: string;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  type?: "memory" | "persona" | "conscious";
}

export interface GetTransactionHistoryParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  page?: number;
  /** Maximum records requested for one server-capped page. */
  pageSize?: number;
  sortBy?: string;
  /** Sort direction; supported values depend on the operation. */
  sortOrder?: number;
  useCursorPagination?: boolean;
  /** Opaque pagination cursor value from the previous page (`next_cursor_value`). */
  cursorValue?: string;
  /** Opaque pagination cursor id from the previous page (`next_cursor_id`). */
  cursorId?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  typeFilter?: string;
}

export interface GetUserParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
}

export interface UpdateUserParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** A new email address for the account. Over the Partner API it is saved unverified, and the Partner API never uses it to reset the password. */
  email?: string;
  /** Only a code the MindUpload app emailed to the new address for this account is accepted. The Partner API cannot send one, so leave this out; a wrong code fails the whole update. */
  emailVerificationCode?: string;
  firstName?: string;
  lastName?: string;
  nickname?: string;
  gender?: string;
  birthDate?: number;
  phoneNumber?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
}

export interface AdvanceVoiceInterviewParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Identifies one interview. Returned by start_voice_interview and required by every later call. */
  interviewSessionId?: string;
  /** Which question this call is about. Send back the one you were last given; it makes the call safe to retry. */
  turnIndex?: number;
  /** What the user did with the question: `confirm` accepts the transcript unchanged, `edit` accepts text they corrected, `skip` moves on without an answer, `re_answer` discards the recording and re-serves the same question, and `abort` ends the interview and discards it. `skip`, `re_answer` and `abort` must not carry `confirmed_text`. */
  action?: "confirm" | "edit" | "skip" | "re_answer" | "abort";
  /** The answer text the user accepted, after any correction they made. */
  confirmedText?: string;
}

export interface GenerateVoiceInterviewReportParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Identifies one interview. Returned by start_voice_interview and required by every later call. */
  interviewSessionId?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  /** The owner's answer to whether other people may read this consciousness's description. True publishes the description already written for it; false withdraws it and erases the text. A newly written description is never readable by anybody else until this says so, so the person can read what is being said about them first. */
  shareDescription?: boolean;
  /** Which voice to write in. `first_person` reads as the user themselves and is what a mind-data upload wants; `second_person` addresses them; `third_person` describes them for a reader who was not present and leaves out anything they would not want quoted. */
  person?: "first_person" | "second_person" | "third_person";
}

export interface StartVoiceInterviewParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Ask for a consciousness by name instead of writing up an interview: returns the third-person description of that consciousness, if one has been produced. Any authenticated caller may ask. Only the third-person form is available this way; the first- and second-person forms address the interviewee and are theirs alone. */
  codename?: string;
  /** AI consciousness id as returned by clone operations. */
  cloneId?: string;
  /** Which question set to run. `mind_upload_first_time` is a long first-run interview whose write-up is meant for a mind-data upload; `memory_refresh` and `personality_refresh` are short repeatable ones that ask something different each time; `matchmaking` surfaces what someone values; `guided_reflection` gives them somewhere to think out loud, and is not counseling. */
  templateKey?: "mind_upload_first_time" | "memory_refresh" | "personality_refresh" | "matchmaking" | "guided_reflection";
}

export interface TranscribeVoiceInterviewAnswerParams {
  /** BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages. */
  preferredLanguage?: string;
  /** The end-user's username. */
  username?: string;
  /** The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage. */
  password?: string;
  /** Identifies one interview. Returned by start_voice_interview and required by every later call. */
  interviewSessionId?: string;
  /** The user's recorded answer, base64-encoded. Discarded after transcription; never stored. */
  answerAudioBase64?: string;
  /** Container of the recording being sent. */
  answerAudioContentType?: string;
}

/**
 * Client for the Mind Upload partner API. Create one with your partner key,
 * then call any operation. Every method resolves to a {@link Result} and
 * rejects with a {@link MindUploadError} subclass on failure.
 */
export class MindUpload extends MindUploadBase {
  // --- AI Consciousnesses ---
  /** Create a new AI consciousness for the user.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  createClone(params: CreateCloneParams = {}): Promise<Result> {
    return this.request("create_clone", params as unknown as Record<string, unknown>);
  }

  /** List the user's AI consciousnesses.
   *
   * Response fields: success, error_message, clones.
   * @see https://docs.mindupload.app
   */
  getClones(params: GetClonesParams = {}): Promise<Result> {
    return this.request("get_clones", params as unknown as Record<string, unknown>);
  }

  /** Update an AI consciousness's profile.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  updateClone(params: UpdateCloneParams = {}): Promise<Result> {
    return this.request("update_clone", params as unknown as Record<string, unknown>);
  }

  // --- Account ---
  /** Check your partner API rate limits, credit caps, and current usage.
   *
   * Response fields: success, error_message, per_user_rate_limit_per_min, per_user_daily_credit_cap, partner_rate_limit_per_min, external_authorization_rate_limit_per_min, partner_daily_credit_cap, max_users, registered_users, partner_requests_last_minute, partner_credit_spends_last_day, user, user_requests_last_minute, user_credit_spends_last_day, credit_spending_tasks, calls_enabled, call_minutes_cap_monthly, call_max_concurrent_sessions, call_voice_minutes_cap_monthly, call_video_minutes_cap_monthly, call_voice_participant_minutes_this_month, call_video_participant_minutes_this_month, call_month_start_timestamp, call_sessions_this_month, call_participant_minutes_this_month, call_live_participant_minutes, call_data_transferred_bytes_this_month, call_data_transferred_is_complete, call_live_sessions, call_spending_tasks, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  getQuota(params: GetQuotaParams = {}): Promise<Result> {
    return this.request("get_quota", params as unknown as Record<string, unknown>);
  }

  // --- Authentication ---
  /** Check whether a username is still available before registering.
   *
   * Response fields: success, error_message, exists, disabled, rate_limited, flood_window, wait_seconds, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  checkUsername(params: CheckUsernameParams = {}): Promise<Result> {
    return this.request("check_username", params as unknown as Record<string, unknown>);
  }

  /** Sign a user in and receive a session token (JWT) for subsequent calls.
   *
   * Response fields: success, error_message, jwt, decrypted_user.
   * @see https://docs.mindupload.app
   */
  login(params: LoginParams = {}): Promise<Result> {
    return this.request("login", params as unknown as Record<string, unknown>);
  }

  /** End the current user session.
   *
   * Response fields: success, error_message, revoked, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  logout(params: LogoutParams = {}): Promise<Result> {
    return this.request("logout", params as unknown as Record<string, unknown>);
  }

  /** Create a user account on your platform.
   *
   * Response fields: success, error_message, jwt, decrypted_user.
   * @see https://docs.mindupload.app
   */
  register(params: RegisterParams = {}): Promise<Result> {
    return this.request("register", params as unknown as Record<string, unknown>);
  }

  // --- Chatrooms ---
  /** Cheaply poll whether the user's chatrooms have new activity.
   *
   * Response fields: success, error_message, server_time, poll_config, chatrooms.
   * @see https://docs.mindupload.app
   */
  checkChatroomUpdates(params: CheckChatroomUpdatesParams = {}): Promise<Result> {
    return this.request("check_chatroom_updates", params as unknown as Record<string, unknown>);
  }

  /** Create a chatroom.
   *
   * Response fields: success, error_message, chatroom_id.
   * @see https://docs.mindupload.app
   */
  createChatroom(params: CreateChatroomParams = {}): Promise<Result> {
    return this.request("create_chatroom", params as unknown as Record<string, unknown>);
  }

  /** Invite a user or an AI consciousness into a chatroom.
   *
   * Response fields: success, error_message, membership_id.
   * @see https://docs.mindupload.app
   */
  createChatroomMembership(params: CreateChatroomMembershipParams = {}): Promise<Result> {
    return this.request("create_chatroom_membership", params as unknown as Record<string, unknown>);
  }

  /** Send a message to a chatroom.
   *
   * Response fields: success, error_message, message_id.
   * @see https://docs.mindupload.app
   */
  createChatroomMessage(params: CreateChatroomMessageParams = {}): Promise<Result> {
    return this.request("create_chatroom_message", params as unknown as Record<string, unknown>);
  }

  /** List the members of a chatroom the user belongs to.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, memberships.
   * @see https://docs.mindupload.app
   */
  getChatroomMembership(params: GetChatroomMembershipParams = {}): Promise<Result> {
    return this.request("get_chatroom_membership", params as unknown as Record<string, unknown>);
  }

  /** Fetch messages from a chatroom the user belongs to.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, messages, media_thumbnails, media_fallbacks, since_overflow.
   * @see https://docs.mindupload.app
   */
  getChatroomMessages(params: GetChatroomMessagesParams = {}): Promise<Result> {
    return this.request("get_chatroom_messages", params as unknown as Record<string, unknown>);
  }

  /** Fetch a window of chatroom messages around one message id (for jump-to).
   *
   * Response fields: success, error_message, messages, media_thumbnails, media_fallbacks, anchor_message_id.
   * @see https://docs.mindupload.app
   */
  getChatroomMessagesAround(params: GetChatroomMessagesAroundParams): Promise<Result> {
    return this.request("get_chatroom_messages_around", params as unknown as Record<string, unknown>);
  }

  /** List the chatrooms the user belongs to.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chatrooms.
   * @see https://docs.mindupload.app
   */
  getChatrooms(params: GetChatroomsParams = {}): Promise<Result> {
    return this.request("get_chatrooms", params as unknown as Record<string, unknown>);
  }

  /** Find messages in a chatroom by keyword, date, media type, and/or sender.
   *
   * Response fields: success, error_message, messages, media_thumbnails, media_fallbacks, has_next, next_cursor_value, next_cursor_id, page_size, media_urls_expire_at.
   * @see https://docs.mindupload.app
   */
  searchChatroomMessages(params: SearchChatroomMessagesParams): Promise<Result> {
    return this.request("search_chatroom_messages", params as unknown as Record<string, unknown>);
  }

  /** Translate a text chatroom message into the viewer language.
   *
   * Response fields: success, error_message, translated_text, target_language, cached.
   * @see https://docs.mindupload.app
   */
  translateChatroomMessage(params: TranslateChatroomMessageParams = {}): Promise<Result> {
    return this.request("translate_chatroom_message", params as unknown as Record<string, unknown>);
  }

  // --- Conversation ---
  /** Fetch the one-on-one conversation history with an AI consciousness.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chats, media_thumbnails, media_fallbacks.
   * @see https://docs.mindupload.app
   */
  getChat(params: GetChatParams = {}): Promise<Result> {
    return this.request("get_chat", params as unknown as Record<string, unknown>);
  }

  /** Fetch a window of one-on-one turns around one chat id (for jump-to).
   *
   * Response fields: success, error_message, chats, media_thumbnails, media_fallbacks, anchor_chat_id.
   * @see https://docs.mindupload.app
   */
  getChatAround(params: GetChatAroundParams): Promise<Result> {
    return this.request("get_chat_around", params as unknown as Record<string, unknown>);
  }

  /** Send a message to an AI consciousness and receive its reply.
   *
   * Response fields: success, error_message, response_text, clone_nickname, consolidation_summary, consolidation_count, consolidation_dispatched.
   * @see https://docs.mindupload.app
   */
  rag(params: RagParams = {}): Promise<Result> {
    return this.request("rag", params as unknown as Record<string, unknown>);
  }

  /** Find turns in a one-on-one AI conversation by keyword, date, media type, and/or Human/AI side.
   *
   * Response fields: success, error_message, chats, media_thumbnails, media_fallbacks, has_next, next_cursor_value, next_cursor_id, page_size, media_urls_expire_at.
   * @see https://docs.mindupload.app
   */
  searchChats(params: SearchChatsParams): Promise<Result> {
    return this.request("search_chats", params as unknown as Record<string, unknown>);
  }

  /** Have an AI consciousness proactively join the conversation in a chatroom.
   *
   * Response fields: success, error_message, response_text, chatroom_digests_count, chatroom_digests_summary, consolidation_summary, consolidation_count, consolidation_dispatched.
   * @see https://docs.mindupload.app
   */
  triggerSocial(params: TriggerSocialParams = {}): Promise<Result> {
    return this.request("trigger_social", params as unknown as Record<string, unknown>);
  }

  // --- External Authorization ---
  /** Start passwordless grant issuance for an external identity and installation.
   *
   * Response fields: success, error_message, device_code, user_code, verification_uri, verification_uri_complete, expires_in, poll_interval, grant_duration_seconds.
   * @see https://docs.mindupload.app
   */
  createExternalAuthorizationRequest(params: CreateExternalAuthorizationRequestParams): Promise<Result> {
    return this.request("create_external_authorization_request", params as unknown as Record<string, unknown>);
  }

  /** Poll owner consent and exchange an approval for a clone-scoped grant token.
   *
   * Response fields: success, error_message, status, access_token, refresh_token, token_type, grant_id, scopes, clone_ids, clone_nicknames, access_token_expires_at, expires_at, poll_interval.
   * @see https://docs.mindupload.app
   */
  exchangeExternalAuthorization(params: ExchangeExternalAuthorizationParams): Promise<Result> {
    return this.request("exchange_external_authorization", params as unknown as Record<string, unknown>);
  }

  /** Inspect the scopes, clone resources, expiry, and revocation state of a grant token.
   *
   * Response fields: success, error_message, grant_id, status, scopes, clone_ids, created_at, access_token_expires_at, expires_at, revoked_at.
   * @see https://docs.mindupload.app
   */
  inspectExternalAuthorization(params: InspectExternalAuthorizationParams): Promise<Result> {
    return this.request("inspect_external_authorization", params as unknown as Record<string, unknown>);
  }

  /** Send one idempotent text event to an owner-approved AI consciousness.
   *
   * Response fields: success, error_message, invocation_id, status, response_text, clone_id, clone_nickname, generated_by_ai, idempotent_replay, retry_after_seconds.
   * @see https://docs.mindupload.app
   */
  invokeExternalClone(params: InvokeExternalCloneParams): Promise<Result> {
    return this.request("invoke_external_clone", params as unknown as Record<string, unknown>);
  }

  /** Refresh a short-lived clone-invocation access token.
   *
   * Response fields: success, error_message, status, access_token, refresh_token, token_type, grant_id, scopes, clone_ids, clone_nicknames, access_token_expires_at, expires_at.
   * @see https://docs.mindupload.app
   */
  refreshExternalAuthorization(params: RefreshExternalAuthorizationParams): Promise<Result> {
    return this.request("refresh_external_authorization", params as unknown as Record<string, unknown>);
  }

  /** Upload mind data (text and media) into the owner's own AI consciousness.
   *
   * Response fields: success, error_message, clone_id, text_type, pending_owner_review.
   * @see https://docs.mindupload.app
   */
  uploadExternalMindData(params: UploadExternalMindDataParams): Promise<Result> {
    return this.request("upload_external_mind_data", params as unknown as Record<string, unknown>);
  }

  // --- Insights ---
  /** Fetch the mind-graph visualization data of an AI consciousness.
   *
   * Response fields: success, error_message, root_node_id, node, children, texts, total_texts, texts_offset, has_more_texts, is_building.
   * @see https://docs.mindupload.app
   */
  getMindCluster(params: GetMindClusterParams = {}): Promise<Result> {
    return this.request("get_mind_cluster", params as unknown as Record<string, unknown>);
  }

  /** Generate or fetch the compatibility report between two chatroom members.
   *
   * Response fields: success, error_message, report, report_generated_at, is_generating, charged.
   * @see https://docs.mindupload.app
   */
  getSoulmateReport(params: GetSoulmateReportParams = {}): Promise<Result> {
    return this.request("get_soulmate_report", params as unknown as Record<string, unknown>);
  }

  // --- Live calls ---
  /** Start a live voice and video call in a chatroom, or join the one already running.
   *
   * Response fields: success, error_message, call_session_id, auth_token, participant_id, expires_at, is_host, call_session.
   * @see https://docs.mindupload.app
   */
  createCallSession(params: CreateCallSessionParams = {}): Promise<Result> {
    return this.request("create_call_session", params as unknown as Record<string, unknown>);
  }

  /** End a live call for everyone in it.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  endCallSession(params: EndCallSessionParams = {}): Promise<Result> {
    return this.request("end_call_session", params as unknown as Record<string, unknown>);
  }

  /** Check whether a chatroom has a live call, and how many people are in it.
   *
   * Response fields: success, error_message, call_session.
   * @see https://docs.mindupload.app
   */
  getActiveCallSession(params: GetActiveCallSessionParams = {}): Promise<Result> {
    return this.request("get_active_call_session", params as unknown as Record<string, unknown>);
  }

  /** Join a live call that is already running in a chatroom.
   *
   * Response fields: success, error_message, call_session_id, auth_token, participant_id, expires_at, is_host, call_session.
   * @see https://docs.mindupload.app
   */
  joinCallSession(params: JoinCallSessionParams = {}): Promise<Result> {
    return this.request("join_call_session", params as unknown as Record<string, unknown>);
  }

  /** Say that this person has left a call the others are still in.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  leaveCallSession(params: LeaveCallSessionParams = {}): Promise<Result> {
    return this.request("leave_call_session", params as unknown as Record<string, unknown>);
  }

  /** Get a fresh joining pass for a call, before the current one expires.
   *
   * Response fields: success, error_message, call_session_id, auth_token, participant_id, expires_at, is_host.
   * @see https://docs.mindupload.app
   */
  refreshCallToken(params: RefreshCallTokenParams = {}): Promise<Result> {
    return this.request("refresh_call_token", params as unknown as Record<string, unknown>);
  }

  /** Make somebody a co-host of a live call, or stand them down again.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  setCallHost(params: SetCallHostParams = {}): Promise<Result> {
    return this.request("set_call_host", params as unknown as Record<string, unknown>);
  }

  // --- Media ---
  /** Cancel a multipart upload and discard its parts.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  abortMultipartUpload(params: AbortMultipartUploadParams = {}): Promise<Result> {
    return this.request("abort_multipart_upload", params as unknown as Record<string, unknown>);
  }

  /** Cancel a pending upload.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  cancelUpload(params: CancelUploadParams = {}): Promise<Result> {
    return this.request("cancel_upload", params as unknown as Record<string, unknown>);
  }

  /** Finish a multipart upload.
   *
   * Response fields: success, error_message, media_url.
   * @see https://docs.mindupload.app
   */
  completeMultipartUpload(params: CompleteMultipartUploadParams = {}): Promise<Result> {
    return this.request("complete_multipart_upload", params as unknown as Record<string, unknown>);
  }

  /** List the parts already uploaded in a multipart upload.
   *
   * Response fields: success, error_message, parts.
   * @see https://docs.mindupload.app
   */
  listUploadParts(params: ListUploadPartsParams = {}): Promise<Result> {
    return this.request("list_upload_parts", params as unknown as Record<string, unknown>);
  }

  /** Start a large-file upload in multiple parts.
   *
   * Response fields: success, error_message, upload_id, r2_key, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url.
   * @see https://docs.mindupload.app
   */
  requestMultipartUpload(params: RequestMultipartUploadParams = {}): Promise<Result> {
    return this.request("request_multipart_upload", params as unknown as Record<string, unknown>);
  }

  /** Request an upload slot and a signed viewing link for a media attachment.
   *
   * Response fields: success, error_message, r2_key, presigned_url, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url.
   * @see https://docs.mindupload.app
   */
  requestUploadUrl(params: RequestUploadUrlParams = {}): Promise<Result> {
    return this.request("request_upload_url", params as unknown as Record<string, unknown>);
  }

  /** Get the signed link for one part of a multipart upload.
   *
   * Response fields: success, error_message, presigned_url.
   * @see https://docs.mindupload.app
   */
  signUploadPart(params: SignUploadPartParams = {}): Promise<Result> {
    return this.request("sign_upload_part", params as unknown as Record<string, unknown>);
  }

  /** Get signed links for several parts of a multipart upload at once.
   *
   * Response fields: success, error_message, presigned_urls.
   * @see https://docs.mindupload.app
   */
  signUploadPartsBatch(params: SignUploadPartsBatchParams = {}): Promise<Result> {
    return this.request("sign_upload_parts_batch", params as unknown as Record<string, unknown>);
  }

  /** Begin analysing an uploaded or linked attachment so its description is ready before the message is sent.
   *
   * Response fields: success, error_message, analyses.
   * @see https://docs.mindupload.app
   */
  startMediaAnalysis(params: StartMediaAnalysisParams): Promise<Result> {
    return this.request("start_media_analysis", params as unknown as Record<string, unknown>);
  }

  // --- Memories ---
  /** Upload a memory or persona entry to an AI consciousness.
   *
   * Response fields: success, error_message, cluster_label, cluster_modified_count.
   * @see https://docs.mindupload.app
   */
  createText(params: CreateTextParams = {}): Promise<Result> {
    return this.request("create_text", params as unknown as Record<string, unknown>);
  }

  /** List the memories and persona entries uploaded to an AI consciousness.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, texts.
   * @see https://docs.mindupload.app
   */
  getTexts(params: GetTextsParams = {}): Promise<Result> {
    return this.request("get_texts", params as unknown as Record<string, unknown>);
  }

  // --- Users ---
  /** List the user's Rabbit balance history (top-ups, spending, earnings, withdrawals, tax), newest first, filterable by category and paged with a cursor.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, transactions, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  getTransactionHistory(params: GetTransactionHistoryParams = {}): Promise<Result> {
    return this.request("get_transaction_history", params as unknown as Record<string, unknown>);
  }

  /** Fetch the signed-in user's profile.
   *
   * Response fields: success, error_message, jwt, decrypted_user.
   * @see https://docs.mindupload.app
   */
  getUser(params: GetUserParams = {}): Promise<Result> {
    return this.request("get_user", params as unknown as Record<string, unknown>);
  }

  /** Update the signed-in user's profile.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  updateUser(params: UpdateUserParams = {}): Promise<Result> {
    return this.request("update_user", params as unknown as Record<string, unknown>);
  }

  // --- Voice Interviews ---
  /** Accept, edit, skip, re-record or abandon the question the user is on, and receive the next one.
   *
   * Response fields: success, error_message, interview_session_id, template_key, language, turn_index, question_text, question_audio_url, question_audio_content_type, progress, is_complete, is_resumed, status, safety_message.
   * @see https://docs.mindupload.app
   */
  advanceVoiceInterview(params: AdvanceVoiceInterviewParams = {}): Promise<Result> {
    return this.request("advance_voice_interview", params as unknown as Record<string, unknown>);
  }

  /** Write a finished interview up as prose, in first, second or third person.
   *
   * Response fields: success, error_message, interview_session_id, person, report_text, text_type, is_raw_answers.
   * @see https://docs.mindupload.app
   */
  generateVoiceInterviewReport(params: GenerateVoiceInterviewReportParams = {}): Promise<Result> {
    return this.request("generate_voice_interview_report", params as unknown as Record<string, unknown>);
  }

  /** Begin a spoken interview with one of your end-users, or hand back one they have not finished with.
   *
   * Response fields: success, error_message, interview_session_id, template_key, language, turn_index, question_text, question_audio_url, question_audio_content_type, progress, is_complete, is_resumed, status.
   * @see https://docs.mindupload.app
   */
  startVoiceInterview(params: StartVoiceInterviewParams = {}): Promise<Result> {
    return this.request("start_voice_interview", params as unknown as Record<string, unknown>);
  }

  /** Turn one recorded spoken answer into text for the user to check before it is accepted.
   *
   * Response fields: success, error_message, recognized_text.
   * @see https://docs.mindupload.app
   */
  transcribeVoiceInterviewAnswer(params: TranscribeVoiceInterviewAnswerParams = {}): Promise<Result> {
    return this.request("transcribe_voice_interview_answer", params as unknown as Record<string, unknown>);
  }

  /** Poll owner consent at the server-advised cadence until exchange succeeds. */
  async waitForExternalAuthorization(
    params: WaitForExternalAuthorizationParams,
  ): Promise<Result> {
    const deadline = Date.now() + (params.timeoutMs ?? 600000);
    let pollIntervalMs = DEFAULT_AUTHORIZATION_POLL_MS;
    // Poll sequentially because every response controls the next
    // server-advised delay.
    for (;;) {
      const result = await this.exchangeExternalAuthorization({
        deviceCode: params.deviceCode,
      });
      const status = result.status as ExternalAuthorizationStatus;
      if (status === "exchanged") return result;
      if (status === "denied" || status === "expired" || status === "revoked") {
        throw new MindUploadError(
          `External authorization ended with status: ${status}`,
          { operation: "exchange_external_authorization", response: result },
        );
      }
      const serverIntervalMs = Number(
        result.poll_interval ?? DEFAULT_AUTHORIZATION_POLL_MS / 1000,
      ) * 1000;
      if (status === "slow_down") {
        pollIntervalMs = Math.max(serverIntervalMs, Math.min(
          pollIntervalMs + SLOW_DOWN_INCREMENT_MS,
          MAX_SLOW_DOWN_POLL_MS,
        ));
      } else {
        pollIntervalMs = Math.max(serverIntervalMs, Math.min(
          pollIntervalMs * 1.5,
          MAX_PENDING_POLL_MS,
        ));
      }
      const waitMs = pollIntervalMs * (1 + Math.random() * POLL_JITTER_RATIO);
      if (Date.now() + waitMs > deadline) {
        throw new Error("Timed out waiting for external authorization.");
      }
      await new Promise((resolve) => setTimeout(resolve, waitMs));
    }
  }

  /** Invoke a clone and wait out slow generation via idempotent retries.
   *
   * A clone reply is generated inside the request, so under load a call can
   * exceed the client or gateway timeout before the reply is ready. Because the
   * invocation is idempotent on idempotencyKey, this re-sends the SAME event
   * until it resolves: a still-generating call returns status "processing" (or
   * times out), and the finished result is replayed once ready. Prefer this over
   * a bare invokeExternalClone when generation may be slow.
   */
  async waitForExternalCloneInvocation(
    params: WaitForExternalCloneInvocationParams,
  ): Promise<Result> {
    const { timeoutMs, ...invokeParams } = params;
    const deadline = Date.now() + (timeoutMs ?? 120000);
    let pollIntervalMs = DEFAULT_INVOCATION_POLL_MS;
    // Sequential retries: the same idempotency key coalesces to one server-side
    // generation and one charge, so re-sending is safe and returns fast while
    // the first call is still generating.
    for (;;) {
      let result: Result | undefined;
      try {
        result = await this.invokeExternalClone(invokeParams);
      } catch (error) {
        // A timeout means generation is still running server-side; a transient
        // gateway fault is also worth replaying. Surface everything else.
        if (error instanceof MindUploadConnectionError) {
          result = undefined;
        } else if (
          error instanceof ApiError &&
          INVOCATION_RETRY_STATUSES.has(error.status)
        ) {
          result = undefined;
        } else {
          throw error;
        }
      }
      if (result && result.status !== EXTERNAL_INVOCATION_PROCESSING_STATUS) {
        return result;
      }
      if (result) {
        // A 0 or absent retry hint falls back to the default (|| not ??),
        // so a missing/zero value never produces a near-busy retry loop.
        pollIntervalMs =
          (Number(result.retry_after_seconds) || DEFAULT_INVOCATION_POLL_MS / 1000) * 1000;
      }
      const waitMs = Math.min(pollIntervalMs, MAX_INVOCATION_POLL_MS) *
        (1 + Math.random() * POLL_JITTER_RATIO);
      if (Date.now() + waitMs > deadline) {
        throw new Error("Timed out waiting for the external clone invocation.");
      }
      await new Promise((resolve) => setTimeout(resolve, waitMs));
    }
  }

}
