// GENERATED by sdk/build.py from openapi.json v1.5.4 — do not edit by hand.
import { MindUploadBase } from "./client";
import type { Result } from "./client";

export interface CreateCloneParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  codename?: string;
  nickname?: string;
  gender?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
}

export interface GetClonesParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
}

export interface UpdateCloneParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  codename?: string;
  nickname?: string;
  gender?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
}

export interface GetQuotaParams {
  preferredLanguage?: string;
  username?: string;
}

export interface CheckUsernameParams {
  preferredLanguage?: string;
  username?: string;
}

export interface LoginParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
}

export interface LogoutParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
}

export interface RegisterParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  email?: string;
  emailVerificationCode?: string;
  firstName?: string;
  lastName?: string;
  nickname?: string;
  gender?: string;
  birthDate?: number;
  phoneNumber?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
}

export interface CheckChatroomUpdatesParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  chatrooms?: Record<string, unknown>[];
}

export interface CreateChatroomParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  chatroomName?: string;
  isPublic?: boolean;
  avatarId?: string;
  soulmateCheckEnabled?: boolean;
}

export interface CreateChatroomMembershipParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  chatroomId?: string;
  inviteeUsername?: string;
  inviteeCodename?: string;
  adminLevel?: string;
}

export interface CreateChatroomMessageParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  chatroomId?: string;
  text?: string;
}

export interface GetChatroomMembershipParams {
  preferredLanguage?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: number;
  useCursorPagination?: boolean;
  cursorValue?: string;
  cursorId?: string;
  username?: string;
  password?: string;
  chatroomId?: string;
}

export interface GetChatroomMessagesParams {
  preferredLanguage?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: number;
  useCursorPagination?: boolean;
  cursorValue?: string;
  cursorId?: string;
  username?: string;
  password?: string;
  chatroomId?: string;
  sinceValue?: number;
  sinceId?: string;
}

export interface GetChatroomsParams {
  preferredLanguage?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: number;
  useCursorPagination?: boolean;
  cursorValue?: string;
  cursorId?: string;
  username?: string;
  password?: string;
  getPublic?: boolean;
  getPrivate?: boolean;
}

export interface TranslateChatroomMessageParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  chatroomId?: string;
  messageId?: string;
}

export interface GetChatParams {
  preferredLanguage?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: number;
  useCursorPagination?: boolean;
  cursorValue?: string;
  cursorId?: string;
  username?: string;
  password?: string;
  codename?: string;
}

export interface RagParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  codename?: string;
  text?: string;
  chatroomId?: string;
}

export interface TriggerSocialParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  membershipId?: string;
  chatroomId?: string;
}

export interface GetMindClusterParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  codename?: string;
  nodeId?: string;
  textsOffset?: number;
  textsPageSize?: number;
  forceRebuild?: boolean;
}

export interface GetSoulmateReportParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  myCloneId?: string;
  otherCloneId?: string;
  chatroomId?: string;
}

export interface AbortMultipartUploadParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  r2Key?: string;
  uploadId?: string;
}

export interface CancelUploadParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  r2Key?: string;
}

export interface CompleteMultipartUploadParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  r2Key?: string;
  uploadId?: string;
  parts?: Record<string, unknown>[];
}

export interface ListUploadPartsParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  r2Key?: string;
  uploadId?: string;
}

export interface RequestMultipartUploadParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  filename?: string;
  contentType?: string;
  fileSizeBytes?: number;
  mediaType?: string;
  hasThumbnail?: boolean;
}

export interface RequestUploadUrlParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  filename?: string;
  contentType?: string;
  fileSizeBytes?: number;
  mediaType?: string;
  hasThumbnail?: boolean;
}

export interface SignUploadPartParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  r2Key?: string;
  uploadId?: string;
  partNumber?: number;
}

export interface SignUploadPartsBatchParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  r2Key?: string;
  uploadId?: string;
  partNumbers?: number[];
}

export interface CreateTextParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  codename?: string;
  cloneId?: string;
  text?: string;
  type?: string;
}

export interface GetTextsParams {
  preferredLanguage?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: number;
  useCursorPagination?: boolean;
  cursorValue?: string;
  cursorId?: string;
  username?: string;
  password?: string;
  codename?: string;
  type?: string;
}

export interface GetUserParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
}

export interface UpdateUserParams {
  preferredLanguage?: string;
  username?: string;
  password?: string;
  email?: string;
  emailVerificationCode?: string;
  firstName?: string;
  lastName?: string;
  nickname?: string;
  gender?: string;
  birthDate?: number;
  phoneNumber?: string;
  avatarId?: string;
  acceptChatroomInvitationByOthers?: boolean;
}

/**
 * Client for the Mind Upload partner API. Create one with your partner key,
 * then call any operation. Every method resolves to a {@link Result} and
 * rejects with a {@link MindUploadError} subclass on failure.
 */
export class MindUpload extends MindUploadBase {
  // --- AI Consciousnesses ---
  /** Create a new AI consciousness for the user.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  createClone(params: CreateCloneParams = {}): Promise<Result> {
    return this.request("create_clone", params as Record<string, unknown>);
  }

  /** List the user's AI consciousnesses.
   *
   * Response fields: success, error_message, clones.
   * @see https://docs.mindupload.app
   */
  getClones(params: GetClonesParams = {}): Promise<Result> {
    return this.request("get_clones", params as Record<string, unknown>);
  }

  /** Update an AI consciousness's profile.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  updateClone(params: UpdateCloneParams = {}): Promise<Result> {
    return this.request("update_clone", params as Record<string, unknown>);
  }

  // --- Account ---
  /** Check your partner API rate limits, credit caps, and current usage.
   *
   * Response fields: success, error_message, per_user_rate_limit_per_min, per_user_daily_credit_cap, partner_rate_limit_per_min, partner_daily_credit_cap, max_users, registered_users, partner_requests_last_minute, partner_credit_spends_last_day, user, user_requests_last_minute, user_credit_spends_last_day, credit_spending_tasks, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  getQuota(params: GetQuotaParams = {}): Promise<Result> {
    return this.request("get_quota", params as Record<string, unknown>);
  }

  // --- Authentication ---
  /** Check whether a username is still available before registering.
   *
   * Response fields: success, error_message, exists, disabled, rate_limited, flood_window, wait_seconds, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  checkUsername(params: CheckUsernameParams = {}): Promise<Result> {
    return this.request("check_username", params as Record<string, unknown>);
  }

  /** Sign a user in and receive a session token (JWT) for subsequent calls.
   *
   * Response fields: success, error_message, jwt, decrypted_user.
   * @see https://docs.mindupload.app
   */
  login(params: LoginParams = {}): Promise<Result> {
    return this.request("login", params as Record<string, unknown>);
  }

  /** End the current user session.
   *
   * Response fields: success, error_message, revoked, operation_duration_ms.
   * @see https://docs.mindupload.app
   */
  logout(params: LogoutParams = {}): Promise<Result> {
    return this.request("logout", params as Record<string, unknown>);
  }

  /** Create a user account on your platform.
   *
   * Response fields: success, error_message, jwt, decrypted_user.
   * @see https://docs.mindupload.app
   */
  register(params: RegisterParams = {}): Promise<Result> {
    return this.request("register", params as Record<string, unknown>);
  }

  // --- Chatrooms ---
  /** Cheaply poll whether the user's chatrooms have new activity.
   *
   * Response fields: success, error_message, server_time, poll_config, chatrooms.
   * @see https://docs.mindupload.app
   */
  checkChatroomUpdates(params: CheckChatroomUpdatesParams = {}): Promise<Result> {
    return this.request("check_chatroom_updates", params as Record<string, unknown>);
  }

  /** Create a chatroom.
   *
   * Response fields: success, error_message, chatroom_id.
   * @see https://docs.mindupload.app
   */
  createChatroom(params: CreateChatroomParams = {}): Promise<Result> {
    return this.request("create_chatroom", params as Record<string, unknown>);
  }

  /** Invite a user or an AI consciousness into a chatroom.
   *
   * Response fields: success, error_message, membership_id.
   * @see https://docs.mindupload.app
   */
  createChatroomMembership(params: CreateChatroomMembershipParams = {}): Promise<Result> {
    return this.request("create_chatroom_membership", params as Record<string, unknown>);
  }

  /** Send a message to a chatroom.
   *
   * Response fields: success, error_message, message_id.
   * @see https://docs.mindupload.app
   */
  createChatroomMessage(params: CreateChatroomMessageParams = {}): Promise<Result> {
    return this.request("create_chatroom_message", params as Record<string, unknown>);
  }

  /** List the members of a chatroom the user belongs to.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, memberships.
   * @see https://docs.mindupload.app
   */
  getChatroomMembership(params: GetChatroomMembershipParams = {}): Promise<Result> {
    return this.request("get_chatroom_membership", params as Record<string, unknown>);
  }

  /** Fetch messages from a chatroom the user belongs to.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, messages, media_thumbnails, since_overflow.
   * @see https://docs.mindupload.app
   */
  getChatroomMessages(params: GetChatroomMessagesParams = {}): Promise<Result> {
    return this.request("get_chatroom_messages", params as Record<string, unknown>);
  }

  /** List the chatrooms the user belongs to.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chatrooms.
   * @see https://docs.mindupload.app
   */
  getChatrooms(params: GetChatroomsParams = {}): Promise<Result> {
    return this.request("get_chatrooms", params as Record<string, unknown>);
  }

  /** Translate a user-authored chatroom message into the viewer language.
   *
   * Response fields: success, error_message, translated_text, target_language, cached.
   * @see https://docs.mindupload.app
   */
  translateChatroomMessage(params: TranslateChatroomMessageParams = {}): Promise<Result> {
    return this.request("translate_chatroom_message", params as Record<string, unknown>);
  }

  // --- Conversation ---
  /** Fetch the one-on-one conversation history with an AI consciousness.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chats, media_thumbnails.
   * @see https://docs.mindupload.app
   */
  getChat(params: GetChatParams = {}): Promise<Result> {
    return this.request("get_chat", params as Record<string, unknown>);
  }

  /** Send a message to an AI consciousness and receive its reply.
   *
   * Response fields: success, error_message, response_text, clone_nickname, consolidation_summary, consolidation_count, consolidation_dispatched.
   * @see https://docs.mindupload.app
   */
  rag(params: RagParams = {}): Promise<Result> {
    return this.request("rag", params as Record<string, unknown>);
  }

  /** Have an AI consciousness proactively join the conversation in a chatroom.
   *
   * Response fields: success, error_message, response_text, chatroom_digests_count, chatroom_digests_summary, consolidation_summary, consolidation_count, consolidation_dispatched.
   * @see https://docs.mindupload.app
   */
  triggerSocial(params: TriggerSocialParams = {}): Promise<Result> {
    return this.request("trigger_social", params as Record<string, unknown>);
  }

  // --- Insights ---
  /** Fetch the mind-graph visualization data of an AI consciousness.
   *
   * Response fields: success, error_message, root_node_id, node, children, texts, total_texts, texts_offset, has_more_texts, is_building.
   * @see https://docs.mindupload.app
   */
  getMindCluster(params: GetMindClusterParams = {}): Promise<Result> {
    return this.request("get_mind_cluster", params as Record<string, unknown>);
  }

  /** Generate or fetch the compatibility report between two chatroom members.
   *
   * Response fields: success, error_message, report, report_generated_at, is_generating, charged.
   * @see https://docs.mindupload.app
   */
  getSoulmateReport(params: GetSoulmateReportParams = {}): Promise<Result> {
    return this.request("get_soulmate_report", params as Record<string, unknown>);
  }

  // --- Media ---
  /** Cancel a multipart upload and discard its parts.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  abortMultipartUpload(params: AbortMultipartUploadParams = {}): Promise<Result> {
    return this.request("abort_multipart_upload", params as Record<string, unknown>);
  }

  /** Cancel a pending upload.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  cancelUpload(params: CancelUploadParams = {}): Promise<Result> {
    return this.request("cancel_upload", params as Record<string, unknown>);
  }

  /** Finish a multipart upload.
   *
   * Response fields: success, error_message, media_url.
   * @see https://docs.mindupload.app
   */
  completeMultipartUpload(params: CompleteMultipartUploadParams = {}): Promise<Result> {
    return this.request("complete_multipart_upload", params as Record<string, unknown>);
  }

  /** List the parts already uploaded in a multipart upload.
   *
   * Response fields: success, error_message, parts.
   * @see https://docs.mindupload.app
   */
  listUploadParts(params: ListUploadPartsParams = {}): Promise<Result> {
    return this.request("list_upload_parts", params as Record<string, unknown>);
  }

  /** Start a large-file upload in multiple parts.
   *
   * Response fields: success, error_message, upload_id, r2_key, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url, message.
   * @see https://docs.mindupload.app
   */
  requestMultipartUpload(params: RequestMultipartUploadParams = {}): Promise<Result> {
    return this.request("request_multipart_upload", params as Record<string, unknown>);
  }

  /** Request an upload slot and a signed viewing link for a media attachment.
   *
   * Response fields: success, error_message, r2_key, presigned_url, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url, message.
   * @see https://docs.mindupload.app
   */
  requestUploadUrl(params: RequestUploadUrlParams = {}): Promise<Result> {
    return this.request("request_upload_url", params as Record<string, unknown>);
  }

  /** Get the signed link for one part of a multipart upload.
   *
   * Response fields: success, error_message, presigned_url.
   * @see https://docs.mindupload.app
   */
  signUploadPart(params: SignUploadPartParams = {}): Promise<Result> {
    return this.request("sign_upload_part", params as Record<string, unknown>);
  }

  /** Get signed links for several parts of a multipart upload at once.
   *
   * Response fields: success, error_message, presigned_urls.
   * @see https://docs.mindupload.app
   */
  signUploadPartsBatch(params: SignUploadPartsBatchParams = {}): Promise<Result> {
    return this.request("sign_upload_parts_batch", params as Record<string, unknown>);
  }

  // --- Memories ---
  /** Upload a memory or persona entry to an AI consciousness.
   *
   * Response fields: success, error_message, cluster_label, cluster_modified_count.
   * @see https://docs.mindupload.app
   */
  createText(params: CreateTextParams = {}): Promise<Result> {
    return this.request("create_text", params as Record<string, unknown>);
  }

  /** List the memories and persona entries uploaded to an AI consciousness.
   *
   * Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, texts.
   * @see https://docs.mindupload.app
   */
  getTexts(params: GetTextsParams = {}): Promise<Result> {
    return this.request("get_texts", params as Record<string, unknown>);
  }

  // --- Users ---
  /** Fetch the signed-in user's profile.
   *
   * Response fields: success, error_message, jwt, decrypted_user.
   * @see https://docs.mindupload.app
   */
  getUser(params: GetUserParams = {}): Promise<Result> {
    return this.request("get_user", params as Record<string, unknown>);
  }

  /** Update the signed-in user's profile.
   *
   * Response fields: success, error_message.
   * @see https://docs.mindupload.app
   */
  updateUser(params: UpdateUserParams = {}): Promise<Result> {
    return this.request("update_user", params as Record<string, unknown>);
  }

}
